//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivePros
    {
        public int ID { get; set; }
        public int ActiveID { get; set; }
        public int ProID { get; set; }
        public string ProName { get; set; }
        public decimal NewPrice { get; set; }
        public string ATitle { get; set; }
        public string AContent { get; set; }
        public string Adecribe { get; set; }
        public int Stock { get; set; }
    }
}
