//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Active
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string SubName { get; set; }
        public System.DateTime StarDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Status { get; set; }
        public string Decribe { get; set; }
        public string Common { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ActiveIMG { get; set; }
    }
}
