//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrowdFunding
    {
        public int ID { get; set; }
        public int Pid { get; set; }
        public System.DateTime ShowTime { get; set; }
        public System.DateTime StarTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<int> isBool { get; set; }
        public string ListTille { get; set; }
        public string Banner { get; set; }
        public Nullable<int> Number { get; set; }
    }
}
