//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberBase
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string LoginName { get; set; }
        public string PassWord { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> MemberType { get; set; }
        public string Ucode { get; set; }
        public int UpUser { get; set; }
        public Nullable<int> Levels { get; set; }
        public Nullable<int> Integral { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string wxOpenid { get; set; }
        public string wxNickname { get; set; }
        public Nullable<int> wxSex { get; set; }
        public string wxProvince { get; set; }
        public string wxCity { get; set; }
        public string wxCountry { get; set; }
        public string wxHeadimgurl { get; set; }
        public string wxPrivilege { get; set; }
    }
}
