//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProList
    {
        public int ID { get; set; }
        public string OrderId { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProductName { get; set; }
        public string SupplyNo { get; set; }
        public int Num { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> InputTime { get; set; }
        public Nullable<int> AttrID { get; set; }
        public string AttrDecribe { get; set; }
        public Nullable<int> PType { get; set; }
        public Nullable<int> IsFlag { get; set; }
        public string activeName { get; set; }
    }
}
