//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPay
    {
        public long id { get; set; }
        public int Uid { get; set; }
        public string Uname { get; set; }
        public string OrderId { get; set; }
        public string PayState { get; set; }
        public string Bank { get; set; }
        public decimal Amount { get; set; }
        public string Remark { get; set; }
        public int PayType { get; set; }
        public int OrderType { get; set; }
        public int RecordState { get; set; }
    }
}
