//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartsExtend
    {
        public int ID { get; set; }
        public int PartID { get; set; }
        public int ParentAttr { get; set; }
        public string AttrName { get; set; }
        public string AttrFlagName { get; set; }
        public string AttrValue { get; set; }
        public decimal AttrPrice { get; set; }
        public int Qty { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> IsMain { get; set; }
    }
}
