//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parts
    {
        public int ID { get; set; }
        public string PartName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string PartTitle { get; set; }
        public string PartSubtitle { get; set; }
        public Nullable<int> PartBrand { get; set; }
        public string PartModel { get; set; }
        public string PartSuppyNo { get; set; }
        public decimal Price { get; set; }
        public string PartNumber { get; set; }
        public string ToCars { get; set; }
        public string Describe { get; set; }
        public string SpecParma { get; set; }
        public string DetailList { get; set; }
        public string SAS { get; set; }
        public string Common { get; set; }
        public Nullable<int> Orderby { get; set; }
        public Nullable<System.DateTime> ShowDate { get; set; }
        public Nullable<int> State { get; set; }
        public string mDescribe { get; set; }
        public Nullable<int> ProType { get; set; }
        public string product_child_json { get; set; }
        public string child_product_dicts { get; set; }
        public string sku { get; set; }
        public string imgProduct { get; set; }
        public Nullable<int> HotProductId { get; set; }
        public Nullable<System.DateTime> insertDate { get; set; }
        public string supply { get; set; }
        public string storeName { get; set; }
        public string material { get; set; }
        public string specifications { get; set; }
        public string useSite { get; set; }
        public string ParsColour { get; set; }
        public string herf { get; set; }
    }
}
