//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneMsg
    {
        public int ID { get; set; }
        public Nullable<int> UID { get; set; }
        public string PhoneNum { get; set; }
        public string Type { get; set; }
        public string Code { get; set; }
        public string MSG { get; set; }
        public string State { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> STime { get; set; }
        public string Port { get; set; }
        public string InfoNumber { get; set; }
    }
}
